services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5601/api/status" ]
      interval: 5s
      timeout: 3s
      retries: 30

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
    depends_on:
      kibana:
       condition: service_healthy
    networks:
      - elastic
    command: filebeat -e --strict.perms=false

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - elastic

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    volumes:
      - ./logs:/app/logs
    networks:
      - elastic
    environment:
      - SERVICE_HOST=server
      - SERVICE_PORT=8080

networks:
  elastic:
    driver: bridge

volumes:
  es_data: