filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /logs/client.json
    tags: ["client"]
    parsers:
      - ndjson:
        keys_under_root: true
        add_error_key: true
        expand_keys: true
  - type: filestream
    enabled: true
    paths:
      - /logs/server.json
    tags: ["server"]
    parsers:
      - ndjson:
        keys_under_root: true
        add_error_key: true
        expand_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true
setup.ilm.enabled: false